image: gitpod/workspace-java-17

tasks:
  - init: mvn -q -DskipTests package
    command: mvn spring-boot:run

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - vscjava.vscode-spring-boot-dashboard
